Repository Projektmodul/Intranet, pull requests merged in 2020-12, with the labels that each got.

#7 editing the fahrplan-content placeholder
  src/main/java/com/example/application/ui/vertical/fahrplan/FahrplanView.java
Labels: good first issue

#8 Changes in MyContactsView
  src/main/java/com/example/application/ui/vertical/myContacts/MyContactsView.java
Labels: enhancement

#15 added Textfield in FavoritsView
  src/main/java/com/example/application/ui/vertical/favorits/FavoritsView.java
Labels: enhancement

#13 Test Kommentar
  src/main/java/com/example/application/ui/vertical/help/HelpView.java
Labels: documentation

#14 Made a comment in app
  src/main/java/com/example/application/ui/vertical/apps/AppsView.java
Labels: enhancement

#12 made a change in CanteenView
  src/main/java/com/example/application/ui/vertical/canteen/CanteenView.java
Labels: enhancement

#11 made some changes in MailingView
  src/main/java/com/example/application/ui/vertical/mailing/MailingView.java
Labels: enhancement

#10 Das ist ein Test-Commit im CalenderView
  src/main/java/com/example/application/ui/vertical/calendar/CalendarView.java
Labels: enhancement

#9 added "TEST" in setID
  src/main/java/com/example/application/ui/vertical/lastVisited/LastVisitedView.java
Labels: enhancement

#16 modified the whole project
  frontend/styles/views/main/main-view.css
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/SideBar.java
Labels: enhancement, help wanted

#17 Feature routen setzen
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/vertical/apps/AppsView.java
  src/main/java/com/example/application/ui/vertical/favorites/FavoritesView.java
Labels: bug, enhancement

#18 remote DB über SSH hinzugefügt
  package-lock.json
  package.json
  pom.xml
  src/main/resources/application.properties
Labels: enhancement

#19 Logo and Home routes.
  frontend/styles/views/main/main-view.css
  src/main/java/com/example/application/ui/MainView.java
Labels: enhancement

#22 Solved conflicts of monika's branch sabrine
  frontend/styles/views/main/main-view.css
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
  src/main/java/com/example/application/ui/vertical/myContacts/MyContactsView.java
Labels: conflicts

#23 Feature notifications sabrine
  frontend/styles/views/main/mainView.css
  frontend/styles/views/main/notification.css
  src/main/java/com/example/application/backend/entities/NotificationEntity.java
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/vertical/notifications/NotificationsView.java
Labels: enhancement

#26 Feature my profile g UI jessica laura
  src/main/java/com/example/application/backend/entities/AddressesEntity.java
  src/main/java/com/example/application/backend/entities/PermissionsEntity.java
  src/main/java/com/example/application/backend/entities/RolesEntity.java
  src/main/java/com/example/application/backend/entities/UsersEntity.java
  src/main/java/com/example/application/backend/entities/UsersRolesEntity.java
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
  src/main/resources/META-INF/resources/images/user.png
Labels: enhancement

#29 added the links in BlogView, PhoneBookView, and TimetableView
  src/main/java/com/example/application/ui/horizontal/community/BlogView.java
  src/main/java/com/example/application/ui/vertical/phoneBook/PhoneBookView.java
  src/main/java/com/example/application/ui/vertical/timetable/TimetableView.java
Labels: enhancement

#28 Feature buttons my profile jessica laura
  frontend/styles/views/main/myProfileView.css
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
Labels: enhancement
