Repository Projektmodul/Intranet, pull requests merged in 2021-02, with the labels that each got.

#117 added a RSS feed in home view
  pom.xml
  src/main/java/com/example/application/ui/HomeView.java
Labels: enhancement

#119 Feature media view laura
  src/main/java/com/example/application/ui/horizontal/library/MediaView.java
Labels: enhancement

#125 Feature set data laura
  frontend/styles/views/main/content.css
  src/main/java/com/example/application/ui/auxiliary/InitData.java
  src/main/java/com/example/application/ui/horizontal/center/CenterIView.java
  src/main/java/com/example/application/ui/horizontal/community/IdeasManagementView.java
  src/main/java/com/example/application/ui/horizontal/library/ArchiveView.java
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
  src/main/java/com/example/application/ui/horizontal/library/FAQView.java
  src/main/java/com/example/application/ui/horizontal/library/MediaView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/CareerView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/SportView.java
Labels: enhancement

#128 Feature chat user jessica
  src/main/java/com/example/application/ui/Header.java
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/presenters/NotificationPresenter.java
Labels: enhancement

#133 Feature news page anastasiya sabrine
  frontend/styles/views/main/content.css
  src/main/java/com/example/application/backend/entities/NewsEntity.java
  src/main/java/com/example/application/backend/entities/PageEntity.java
  src/main/java/com/example/application/backend/repositories/NewsRepository.java
  src/main/java/com/example/application/backend/services/news/NewsService.java
  src/main/java/com/example/application/backend/utils/images/ImageManager.java
  src/main/java/com/example/application/backend/utils/images/ImagesManager.java
  src/main/java/com/example/application/ui/HomeView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/NewsView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsArticle.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsView.java
Labels: documentation, enhancement

#134 Feature fix double images nordlicht
  src/main/java/com/example/application/ui/horizontal/projects/NordlichtView.java
Labels: enhancement, no css

#137 css phonebook icon vanessa
  src/main/java/com/example/application/ui/SideBar.java
Labels: css

#138 Feature fix documents view allgemein bug sabrine
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
Labels: enhancement

#144 Feature add news sabrine
  frontend/styles/views/main/content.css
  src/main/java/com/example/application/backend/entities/NewsEntity.java
  src/main/java/com/example/application/backend/entities/PageEntity.java
  src/main/java/com/example/application/backend/services/news/NewsService.java
  src/main/java/com/example/application/backend/utils/images/Image.java
  src/main/java/com/example/application/backend/utils/images/ImageManager.java
  src/main/java/com/example/application/backend/utils/images/ImagesManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfManager.java
  src/main/java/com/example/application/ui/HomeView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/CareerView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsArticle.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsCreator.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsDeletionDialog.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsDialog.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/news/NewsView.java
Labels: documentation, enhancement

#147 css colorCorrection in Projects vanessa
  src/main/java/com/example/application/ui/horizontal/projects/ProjectsView.java
Labels: css

#148 Feature fix bug career view sabrine
  src/main/java/com/example/application/ui/horizontal/ourCompany/CareerView.java
Labels: enhancement

#153 Fixed the text of the menu notification.
  src/main/java/com/example/application/backend/utils/pdfs/PdfManager.java
Labels: enhancement

#156 update Kommentare --> Parameter näher beschrieben
  src/main/java/com/example/application/backend/services/users/UserService.java
Labels: documentation

#158 Kommentar InitData Klasse
  src/main/java/com/example/application/ui/auxiliary/InitData.java
Labels: documentation

#155 Commentfix ideamanagement jessica
  src/main/java/com/example/application/ui/horizontal/community/IdeasManagementView.java
Labels: documentation

#165 Änderungen in den jeweiligen Dateien sind nur für die war-Datei nötig
  package.json
  pom.xml
  src/main/java/com/example/application/backend/repositories/UserRepository.java
  src/main/java/com/example/application/backend/utils/images/ImageManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfManager.java
  src/main/java/com/example/application/ui/Header.java
  src/main/resources/application.properties
Labels: enhancement

#166 added tests for Login and sidebar
  src/main/java/com/example/application/ui/HomeViewTest.java
  src/main/java/com/example/application/ui/login/LoginViewTest.java
Labels: enhancement
