Repository Projektmodul/Intranet, pull requests merged in 2021-01, with the labels that each got.

#30 Feature implement monikas additions
  frontend/styles/views/main/content.css
  frontend/styles/views/main/mainView.css
  package-lock.json
  src/main/java/com/example/application/ui/ContentHolder.java
  src/main/java/com/example/application/ui/HomeView.java
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/horizontal/center/CenterIView.java
  src/main/java/com/example/application/ui/horizontal/center/CentersView.java
  src/main/java/com/example/application/ui/horizontal/community/BlogView.java
  src/main/java/com/example/application/ui/horizontal/community/CommunityView.java
  src/main/java/com/example/application/ui/horizontal/community/IdeasManagementView.java
  src/main/java/com/example/application/ui/horizontal/community/NoticeBoardView.java
  src/main/java/com/example/application/ui/horizontal/library/ArchiveView.java
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
  src/main/java/com/example/application/ui/horizontal/library/FAQView.java
  src/main/java/com/example/application/ui/horizontal/library/LibraryView.java
  src/main/java/com/example/application/ui/horizontal/library/MediaView.java
  src/main/java/com/example/application/ui/horizontal/library/WikiView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/CareerView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/NewsView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/OurCompanyView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/SportView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/WelcomeView.java
  src/main/java/com/example/application/ui/horizontal/projects/NordlichtView.java
  src/main/java/com/example/application/ui/horizontal/projects/ProjectsView.java
  src/main/java/com/example/application/ui/horizontal/services/BusinessTripsView.java
  src/main/java/com/example/application/ui/horizontal/services/ServicesView.java
  src/main/java/com/example/application/ui/vertical/apps/AppsView.java
  src/main/java/com/example/application/ui/vertical/calendar/CalendarView.java
  src/main/java/com/example/application/ui/vertical/canteen/CanteenView.java
  src/main/java/com/example/application/ui/vertical/favorites/FavoritesView.java
  src/main/java/com/example/application/ui/vertical/help/HelpView.java
  src/main/java/com/example/application/ui/vertical/lastVisited/LastVisitedView.java
  src/main/java/com/example/application/ui/vertical/mailing/MailingView.java
  src/main/java/com/example/application/ui/vertical/myContacts/MyContactsView.java
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
  src/main/java/com/example/application/ui/vertical/phoneBook/PhoneBookView.java
  src/main/java/com/example/application/ui/vertical/search/SearchView.java
  src/main/java/com/example/application/ui/vertical/settings/SettingsView.java
  src/main/java/com/example/application/ui/vertical/timetable/TimetableView.java
Labels: conflicts, enhancement

#32 Added pointer on hovering over logout
  frontend/styles/views/main/mainView.css
Labels: enhancement

#31 Added InProgressView,
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/InProgressView.java
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/horizontal/services/BusinessTripsView.java
  src/main/java/com/example/application/ui/vertical/apps/AppsView.java
  src/main/java/com/example/application/ui/vertical/calendar/CalendarView.java
  src/main/java/com/example/application/ui/vertical/favorites/FavoritesView.java
  src/main/java/com/example/application/ui/vertical/lastVisited/LastVisitedView.java
  src/main/java/com/example/application/ui/vertical/mailing/MailingView.java
  src/main/java/com/example/application/ui/vertical/myContacts/MyContactsView.java
Labels: enhancement

#34 Feature sidebar without pre set vanessa
  src/main/java/com/example/application/ui/SideBar.java
Labels: enhancement

#33 Two routes linked to the wrong pages
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/horizontal/projects/ProjectsView.java
  src/main/java/com/example/application/ui/horizontal/services/ServicesView.java
Labels: enhancement

#39 Feature my profiledatabase connection laura jessica
  src/main/java/com/example/application/backend/entities/PageEntity.java
  src/main/java/com/example/application/backend/entities/UsersEntity.java
  src/main/java/com/example/application/backend/repositories/AddressRepository.java
  src/main/java/com/example/application/backend/repositories/UserRepository.java
  src/main/java/com/example/application/backend/services/addresses/AddressesService.java
  src/main/java/com/example/application/backend/services/myProfile/MyProfileViewService.java
  src/main/java/com/example/application/backend/services/users/UsersService.java
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
Labels: enhancement

#43 Feature my profile database update laura jessica
  .gitignore
  src/main/java/com/example/application/backend/entities/ImageEntity.java
  src/main/java/com/example/application/backend/entities/UserEntity.java
  src/main/java/com/example/application/backend/repositories/UserRepository.java
  src/main/java/com/example/application/backend/services/addresses/AddressService.java
  src/main/java/com/example/application/backend/services/myProfile/MyProfileViewService.java
  src/main/java/com/example/application/backend/services/users/UserService.java
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
Labels: enhancement

#41 Feature canteen frontend sabrine anastasiya
  frontend/styles/views/main/canteen.css
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
  src/main/java/com/example/application/ui/vertical/canteen/CanteenView.java
  src/main/resources/META-INF/resources/images/speiseplanBeispiel.png
Labels: enhancement

#40 Feature documents view frontend sabrine anastasiya
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
Labels: enhancement

#48 AboutViewService Klasse hinzugefügt.
  src/main/java/com/example/application/backend/services/ourCompany/AboutUsViewService.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
Labels: enhancement

#49 set the id of the aboutUs page to 4 instead of 5.
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
Labels: enhancement

#50 Added the notifications functionality directly to the mainView.
  src/main/java/com/example/application/ui/ContentHolder.java
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/presenters/NotificationPresenter.java
Labels: enhancement

#51 Added Listener-Response-System, Minor Changes to css
  frontend/styles/views/main/content.css
  frontend/styles/views/main/mainView.css
  src/main/java/com/example/application/ui/Header.java
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/HorizontalBarClickedInitiator.java
  src/main/java/com/example/application/ui/HorizontalBarClickedListener.java
  src/main/java/com/example/application/ui/MainView.java
  src/main/java/com/example/application/ui/SideBar.java
Labels: enhancement

#53 feature_mailingFahrplaner_vanessa
  frontend/styles/views/main/content.css
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/vertical/mailing/MailingView.java
  src/main/java/com/example/application/ui/vertical/timetable/TimetableView.java
Labels: enhancement

#56 Feature object span jessica laura
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
  src/main/java/com/example/application/ui/horizontal/ourCompany/WelcomeView.java
Labels: enhancement

#58 added the links in PhoneBookView which open a new tab
  src/main/java/com/example/application/ui/vertical/phoneBook/PhoneBookView.java
Labels: enhancement

#63 Feature pdf viewer component
  src/main/java/com/example/application/backend/entities/DocumentEntity.java
  src/main/java/com/example/application/backend/entities/NotificationEntity.java
  src/main/java/com/example/application/backend/entities/PageEntity.java
  src/main/java/com/example/application/backend/services/files/DocumentService.java
  src/main/java/com/example/application/backend/services/files/ImageService.java
  src/main/java/com/example/application/backend/utils/pdfs/PDF.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfCreationManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfDeletionManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfDocumentViewer.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfsManager.java
Labels: enhancement

#54 feature_archive_vanessa
  src/main/java/com/example/application/ui/SideBar.java
  src/main/java/com/example/application/ui/horizontal/library/ArchiveView.java
Labels: enhancement

#66 added the links in BlogView and WikiView which open new tabs
  src/main/java/com/example/application/ui/horizontal/community/BlogView.java
  src/main/java/com/example/application/ui/horizontal/library/WikiView.java
Labels: enhancement

#68 Feature backgroundimage login vanessaJessica
  frontend/styles/views/main/login.css
  src/main/java/com/example/application/ui/login/LoginView.java
  src/main/resources/META-INF/resources/images/nordlicht-bremer-rathaus.jpg
Labels: enhancement

#70 Feature personal welcome jessica laura
  src/main/java/com/example/application/ui/HomeView.java
Labels: enhancement

#71 changed the button for light/dark mode to a switch in SettingsView
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/example/application/ui/vertical/settings/SettingsView.java
Labels: enhancement

#74 Added variable to set if only one pdf file is allowed on the page or …
  src/main/java/com/example/application/backend/utils/pdfs/PdfManager.java
  src/main/java/com/example/application/backend/utils/pdfs/PdfsManager.java
Labels: enhancement

#75 Bei AboutView kann jetzt ein bild hochgeladen werden
  package-lock.json
  package.json
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
Labels: enhancement

#78 Solved conflicts, added new addon of the timeline (this updated the .…
  frontend/styles/views/main/content.css
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
Labels: conflicts, enhancement

#86 Bei den Überschriften und dem Content die Schriftart angepasst.
  frontend/styles/views/main/content.css
Labels: enhancement

#88 Fixed request #87 due to conflicts
  frontend/styles/views/main/content.css
  frontend/styles/views/main/mainView.css
Labels: conflicts, enhancement

#89 fix_myOwnMistake_Vanessa
  src/main/java/com/example/application/ui/vertical/myProfile/MyProfileView.java
Labels: conflicts, enhancement

#91 Feature welcome organigram
  src/main/java/com/example/application/ui/horizontal/ourCompany/WelcomeView.java
Labels: enhancement, no css

#101 Added a default value for the radio button in the documents uploader.
  src/main/java/com/example/application/ui/horizontal/library/DocumentsView.java
Labels: enhancement

#103 Feature project vew button monika laura
  frontend/styles/views/main/content.css
  src/main/java/com/example/application/ui/horizontal/projects/ProjectsView.java
Labels: enhancement

#108 Feature sport und freizeit laura
  src/main/java/com/example/application/ui/horizontal/ourCompany/SportView.java
Labels: enhancement

#110 Feature faq laura
  src/main/java/com/example/application/ui/horizontal/library/FAQView.java
Labels: enhancement, no css

#105 Feature formular designer vanessa
  src/main/java/com/example/application/ui/HorizontalBar.java
  src/main/java/com/example/application/ui/horizontal/services/ServicesView.java
Labels: enhancement

#107 Feature chat vanessa
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/example/application/ui/HorizontalBar.java
Labels: enhancement

#114 cleanUp_contentHolder_vanessa
  src/main/java/com/example/application/ui/ContentHolder.java
Labels: enhancement
